# Generated by Django 5.1.7 on 2025-04-15 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_seniorone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seniorone',
            name='cls',
        ),
    ]
