# Generated by Django 5.1.7 on 2025-04-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_remove_seniorone_cls'),
    ]

    operations = [
        migrations.AddField(
            model_name='seniorone',
            name='father_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Father's Address"),
        ),
        migrations.AddField(
            model_name='seniorone',
            name='father_contact',
            field=models.CharField(default=True, max_length=15, verbose_name="Father's Contact"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seniorone',
            name='father_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="Father's Email"),
        ),
        migrations.AddField(
            model_name='seniorone',
            name='father_name',
            field=models.CharField(default=True, max_length=100, verbose_name="Father's Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seniorone',
            name='father_nin',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name="Father's NIN"),
        ),
        migrations.AddField(
            model_name='seniorone',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Father's Occupation"),
        ),
        migrations.AddField(
            model_name='seniorone',
            name='father_second_contact',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name="Father's Second Contact"),
        ),
        migrations.AddField(
            model_name='seniorone',
            name='father_status',
            field=models.CharField(choices=[('Alive', 'Alive'), ('Deceased', 'Deceased')], default=True, max_length=10, verbose_name="Father's Status"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seniorone',
            name='guardian_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Guardian's Address"),
        ),
        migrations.AddField(
            model_name='seniorone',
            name='guardian_contact',
            field=models.CharField(default=True, max_length=15, verbose_name="Guardian's Contact"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seniorone',
            name='guardian_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="Guardian's Email"),
        ),
        migrations.AddField(
            model_name='seniorone',
            name='guardian_name',
            field=models.CharField(default=True, max_length=100, verbose_name="Guardian's Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seniorone',
            name='guardian_nin',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name="Guardian's NIN"),
        ),
        migrations.AddField(
            model_name='seniorone',
            name='guardian_occupation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Guardian's Occupation"),
        ),
        migrations.AddField(
            model_name='seniorone',
            name='guardian_relationship',
            field=models.CharField(default=True, max_length=100, verbose_name="Guardian's Relationship"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seniorone',
            name='guardian_second_contact',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name="Guardian's Second Contact"),
        ),
        migrations.AddField(
            model_name='seniorone',
            name='mother_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Mother's Address"),
        ),
        migrations.AddField(
            model_name='seniorone',
            name='mother_contact',
            field=models.CharField(default=True, max_length=15, verbose_name="Mother's Contact"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seniorone',
            name='mother_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="Mother's Email"),
        ),
        migrations.AddField(
            model_name='seniorone',
            name='mother_name',
            field=models.CharField(default=True, max_length=100, verbose_name="Mother's Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seniorone',
            name='mother_nin',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name="Mother's NIN"),
        ),
        migrations.AddField(
            model_name='seniorone',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Mother's Occupation"),
        ),
        migrations.AddField(
            model_name='seniorone',
            name='mother_second_contact',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name="Mother's Second Contact"),
        ),
        migrations.AddField(
            model_name='seniorone',
            name='mother_status',
            field=models.CharField(choices=[('Alive', 'Alive'), ('Deceased', 'Deceased')], default=True, max_length=10, verbose_name="Mother's Status"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seniorone',
            name='nok_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Next of Kin Address'),
        ),
        migrations.AddField(
            model_name='seniorone',
            name='nok_contact',
            field=models.CharField(default=True, max_length=15, verbose_name='Next of Kin Contact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seniorone',
            name='nok_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Next of Kin Email'),
        ),
        migrations.AddField(
            model_name='seniorone',
            name='nok_name',
            field=models.CharField(default=True, max_length=100, verbose_name='Next of Kin Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seniorone',
            name='nok_nin',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Next of Kin NIN'),
        ),
        migrations.AddField(
            model_name='seniorone',
            name='nok_occupation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Next of Kin Occupation'),
        ),
        migrations.AddField(
            model_name='seniorone',
            name='nok_relationship',
            field=models.CharField(default=True, max_length=100, verbose_name='Next of Kin Relationship'),
            preserve_default=False,
        ),
    ]
